version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - todo-db
    environment:
      - DB_HOST=todo-db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=tododb
    volumes:
      - ./server/src:/app/src

  client:
    build: ./client
    ports:
      - "8080:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
  todo-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - todo-db-data:/var/lib/mysql
volumes:
  todo-db-data: